# Generated by Django 3.1.5 on 2021-01-19 17:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('crops_name', models.CharField(blank=True, default='', max_length=30)),
                ('N', models.IntegerField()),
                ('t_N', models.IntegerField()),
                ('P', models.IntegerField()),
                ('t_P', models.IntegerField()),
                ('K', models.IntegerField()),
                ('t_K', models.IntegerField()),
                ('S', models.IntegerField()),
                ('t_S', models.IntegerField()),
                ('pH', models.FloatField()),
                ('t_pH', models.FloatField()),
                ('moisture', models.IntegerField()),
                ('t_moisture', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='soildata',
            name='n_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
