# Generated by Django 3.1.5 on 2021-01-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210119_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soildata',
            name='time',
        ),
    ]
