# Generated by Django 3.1.5 on 2021-01-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210119_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soildata',
            old_name='time',
            new_name='l_time',
        ),
    ]
