# Generated by Django 3.1.5 on 2021-01-19 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210120_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soildata',
            name='l_time',
        ),
        migrations.AddField(
            model_name='soildata',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
