# Generated by Django 3.1.5 on 2021-01-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210120_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropsData',
            new_name='CropData',
        ),
    ]
