# Generated by Django 3.1.5 on 2021-01-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210120_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropData',
            new_name='CropsData',
        ),
    ]
