# Generated by Django 3.1.5 on 2021-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210120_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
