# Generated by Django 3.1.5 on 2021-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210217_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
        migrations.AddField(
            model_name='farmer',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='farmer',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='farmer',
            name='postal_code',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
