# Generated by Django 3.1.5 on 2021-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210319_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
