# Generated by Django 3.1.5 on 2021-03-19 20:59

from django.db import migrations, models
import smart_agro.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210319_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/assets/img/blank-profile-picture.png', upload_to=smart_agro.core.models.profile_image_upload_to),
        ),
    ]
