# Generated by Django 3.1.5 on 2021-03-19 22:18

from django.db import migrations, models
import smart_agro.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_farmer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/blank-profile-picture.png', upload_to=smart_agro.core.models.profile_image_upload_to),
        ),
    ]
